name: End to End CI/CD workflow for Java Applicaton with Maven, Sonar and k8s Intergation

on:
  push:
    branches:
      - main
env:
  KUBECONFIG: ${{ secrets.KUBECONFIG }}
  SONAR_TOKEN: ${{ secrets.SONAR_TKN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Java jdk setup
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    - name: Run Tests
      run:  mvn test
  #  - name: Build with Maven
   #   run:  mvn build

#    - name: Perform analysis on Sonar Qube
#      uses: sonarsource/sonarcloud-github-action@v1
 #     uses: SonarSource/sonarcloud-github-action@master
 #     with:
 #       sonarcloud.organization: <name of your org>
  #      sonarcloud.projectKey: <key>
   #     sonarcloud.projectName: <name>
    #    sonarcloud.token: ${{ env.SONAR_TKN }}
     #   sonarcloud.scannerVersion: "4.2.0.1873"
     

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

    #  - name: Set up kubectl
     #   run: echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml && export KUBECONFIG=$(pwd)/kubeconfig.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f path/to/your/k8s/manifests
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
